### ISSUE TITLE
How to implement image input for the multimodal local model ? 

### ISSUE THREAD

**Issue by reachsak** [tyrell/llm-ollama-llamaindex-bootstrap-ui#1]
I'm trying to embeded both images and caption with RAG.  I want the final RAG app to be able to receive images as input and provide a more context-aware answer (beyond the native multimodel model) based on the images and text in the vector store. How can we implement the image input here in the app ? 
Thank you

**Comment by tyrell** [comment]
The current version of this project doesn't support images. I'm planning to uplift this to a multi-model example, when I get some free time. 

If you make progress, please feel free to submit a pull request.
