### ISSUE TITLE
ImportError: cannot import name 'VectorStoreIndex' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by yangboz** [tyrell/llm-ollama-llamaindex-bootstrap-ui#2]
first off , thanks for your sharing this full stack open source project , after running the backend using python ```unicorn main:app --reload``,some errors happen as following:
 
```
 from app.api.routers.chat import chat_router
  File "/Users/yangboz/git/llm-ollama-llamaindex-bootstrap-ui/backend/app/api/routers/chat.py", line 6, in <module>
    from app.utils.index import get_index
  File "/Users/yangboz/git/llm-ollama-llamaindex-bootstrap-ui/backend/app/utils/index.py", line 2, in <module>
    from llama_index import VectorStoreIndex, ServiceContext
ImportError: cannot import name 'VectorStoreIndex' from 'llama_index' (unknown location)
```

any idea ? may be llama_index related ?

**Comment by tyrell** [comment]
Hello, did you run the RAG pipeline from my other project at https://github.com/tyrell/llm-ollama-llamaindex-bootstrap to create an index? If not please clone that repository and follow the instructions to create the example index.

**Comment by yangboz** [comment]
ok , I fix it by myself ,   it is from llama_index.core import VectorStoreIndex
